# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRy2QX10hPpeDw2t6tZWwpcmXesWa3IU
"""

### Día 1

### Temario:
- Tipos de datos
- Operaciones matemáticas
- Operaciones con string
- Operaciones lógicas
- Operaciones lógicas

# Existen los datos:
enteros = 10 # int
flotantes = 83. # float
type(flotantes)

##### Caracteres/strings:
caracteres = "@caracteres" ## string
cadena_caracteres = "ESto es una cadena"
type(cadena_caracteres)

#### Booleanos

booleanoF = False
booleanoT = True

type(booleanoT)

### Imprimir (print)
print("imprimiendo...")

#### ¿Cómo ingresar datos? Con la función input(), el usuario puede ingresar cualquier tipo de dato
ingresado = int(input("Mi nombre es:"))
print(ingresado)


print(ingresado + 1)

"""Operaciones matemáticas:"""

# Suma ordinaria (4to nivel de importancia):
suma = 1 + 3
print(1 + 3)

variable1, variable2 = 1, 5

sumado = variable1 + variable2
print(sumado)

# Resta ordinaria:
print(6 - 9)
v1 = 5
v2 = 7
resultados = v1 - v2
print(resultados)

# Tercer nivel de importancia
## Multiplicación ordinaria:

m1, m2 = 1, 3.14
print(m1 * m2)

# Division ordinaria:
m1,m2,m3,m4,m5,m6 = 2,5,6,5,4,5

print(m4 / m3)
print(m5 / m2)
print(m6 / m1)

# División de piso:
divpiso = (m1 // m2)
print(f"la división de piso es: {divpiso}")

# potencias:
print("Potencias")

p1 = 1
p2 = 2
print(p2 ** p2)

### Area de un circulo:

pi = 3.1416
r = 4
A = pi * r * r

print(A)

#### Concat
HM = "Hola mundo"
print(HM)

H = "Hola"
M = "Mundo"

print(H + " " + M)

Animal = "GAto"
Nombre = "Felino"
Fruta = "Mango"
Profesion = "Carpintero"

print(f"Hoola, soy un {Animal}, soy un {Nombre}, me gusta la fruta: {Fruta}, y soy un: {Profesion}")

"""***Operaciones lógicas**"""

# Los operadores lógicos son: >, <, >=, <=

b1 = 3 < 4

print(b1)

### Ejercicio:

Pan = True
Queso = True
Jamon = False
Papas = False

print("¿Tengo suficientes ingredientes para el zandwich?")

if Pan and Queso and Jamon and Papas:
  print("Tengo todos los ingredientes")
  else:
    print("Me hacen falta ingredientes para el zandwich")

print(True * 20)
print(False * 20)