# -*- coding: utf-8 -*-
"""dia2condicionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13j5GYNfu7HurfQtoDnYCwb1eMGUXeVGT

Condicional if
"""

if 5 > 4:
  print("Es correcto!")
else:
  print("Es falso!")

"""Los condicionales sirven parqa evaluar operadores lógicos.

Supongamos que compras un café, pero quieres leche deslactosada, pero tiene costo extra.
"""

leche_deslac = True
cafe = 50
if leche_deslac:
  cafe += 5
  print("Se agrega un costo extra de 5 pesos.")
print(f"Se pagará: {cafe}")

"""**-if else-**
Es lo que pasa si no se cumple una condicion.
"""

#Notas de materias:
nota = float(input("Ingresa una nota:"))

if nota >= 70:
  print("Acreditaste la materia!")
else: #Si es menor a 70
  print("No acreditaste")

edad = int(input("Introduce tu edad"))

if edad >= 18:
  print("Eres mayor de edad")
  if edad >= 65:
    print("Eres adulto mayor")
  else:
    print("Adulto no mayor")
else:
  print("Eres menor de edad")
  if edad <= 12:
    print("Eres un niñato chaval")
  else:
    print("Eres un adolescente")

"""ELIF

Hagamos un algoritmo que pida la edad del usuario y determine el equivalente en el sistema estadounidense usando ELIF
"""

calif = int(input("Introduce tu calificacion"))

if calif == 100:
  print("A+")
elif calif >= 90 and calif < 100:
  print("A")
elif calif >= 80 and calif < 90:
  print("B")
elif calif >= 70 and calif < 80:
  print("C")
elif calif >= 60 and calif < 70:
  print("D")
else:
  print("F")

"""Operadores lógicos con condicionales"""

pan = True
jamon = False
queso = True
mayonesa = True

if not (pan and mayonesa and queso and jamon):
  print("No te puedes hacer el zandwich")

calif = int(input("Introduce tu calificacion"))
if calif >= 0 and calif <= 100:
  if calif == 100:
    print("A+")
  elif calif >= 90 and calif < 100:
    print("A")
  elif calif >= 80 and calif < 90:
    print("B")
  elif calif >= 70 and calif < 80:
    print("C")
  elif calif >= 60 and calif < 70:
    print("D")
  else:
    print("F")
else:
  print("Dato inválido")

# El módulo es el residuo de una división (%)

num = 9
if (num % 3) == 0:
  print("El número es divisible entre 3")
else:
  print("El numero no es divisible entre 3")

# Saber si un número es par o impar

if (num % 2) == 0:
  print("El número es impar")

"""Ciclo FOR:

El ciclo for nos ayuda a repetir una serie de acciones una cantidad determinada de veces.
"""

# FOR inicia siempre en 0

for i in range(5):
  print(i)

for num in range(2,11):
  print(num)


#Usando cadenas:

cadena_pr = "Python :)"

for letra in cadena_pr:
  print(letra)

# También existe el range. (inicio,fin,paso)

for i in range(0,100,2):
  print(i)

"""Ciclo WHILE"""

# El ciclo WHILE se repite mientras cierta condicion sea cierta.

suma = 0

while numero != 0 and suma < 100:
  numero = int(input("Introduce un númnero para la suma o 0 para salir"))
  suma += numero
  print("suma acumulada: ",suma)


print("La suma final es:",suma)
print("Finalizando programa...")

suma = 0